table Invoice
	lineageTag: 8f8e7454-e080-4b7d-992c-c1a39e164594

	measure 'Units Sold' = ```
			SUM ( 'Invoice'[Units] ) 
			```
		formatString: #,0
		displayFolder: Measures\Base
		lineageTag: fb5c586c-a915-4bab-8be1-9605a241bce6

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Revenue = ```
			
			SUMX ( 
			    'Invoice'
			    , 'Invoice'[Units] * 'Invoice'[ExtPrice]
			)
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Measures\Base
		lineageTag: a1fb8013-03df-41c3-9a8f-6cd1c31ab8df

	measure 'Units Sold PY' = ```
			
			VAR _maxdate = 
			MIN ( 
			    MAX ( 'Date'[date] ) 
			    , DATE ( 2026, 03, 25 ) -- TODAY()
			)
			VAR _mindate = MIN ( 'Date'[date] )
			VAR _maxdatePY = DATE ( YEAR ( _maxdate ) - 1, MONTH ( _maxdate ), DAY ( _maxdate ) )
			VAR _mindatePY = DATE ( YEAR ( _mindate ) - 1, MONTH ( _mindate ) , DAY ( _mindate ) ) 
			VAR _dates = 
			FILTER ( 
			    ALL ( 'Date' ) 
			    , 'Date'[date] >= _mindatePY
			        && 'Date'[date] <= _maxdatePY
			)
			VAR _result = 
			SUMX ( 
			    _dates
			    , [Units Sold]
			)
			
			RETURN
			_result 
			```
		formatString: #,0
		displayFolder: Measures\Base
		lineageTag: f64fc2f5-d6d7-4021-babd-4bdb26bced2d

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Revenue PY' = ```
			
			VAR _maxdate = 
			MIN ( 
			    MAX ( 'Date'[date] ) 
			    , DATE ( 2026, 03, 25 ) -- TODAY()
			)
			VAR _mindate = MIN ( 'Date'[date] )
			VAR _maxdatePY = DATE ( YEAR ( _maxdate ) - 1, MONTH ( _maxdate ), DAY ( _maxdate ) )
			VAR _mindatePY = DATE ( YEAR ( _mindate ) - 1, MONTH ( _mindate ) , DAY ( _mindate ) ) 
			VAR _dates = 
			FILTER ( 
			    ALL ( 'Date' ) 
			    , 'Date'[date] >= _mindatePY
			        && 'Date'[date] <= _maxdatePY
			)
			VAR _result = 
			SUMX ( 
			    _dates
			    , [Revenue]
			)
			
			RETURN
			_result 
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Measures\Base
		lineageTag: bfd5941e-df64-4799-be22-51b9c02ca833

	measure 'Units PMTD' = ```
			
			CALCULATE ( 
			    [Units Sold]
			    , 'Date'[month_offset] = -1
			)
			
			/*
			VAR _tbl = 
			FILTER ( 
			    'Date' 
			    , 'Date'[month_offset] = -1
			)
			VAR _result = 
			SUMX ( 
			    _tbl
			    , [Units Sold]
			)
			
			RETURN
			_result
			*/
			```
		formatString: #,0
		displayFolder: Measures\Time Intelligence
		lineageTag: 69c86d80-b5d3-46ba-85a2-4f495ebd09ff

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Units MTD' = ```
			
			CALCULATE ( 
			    [Units Sold]
			    , 'Date'[month_offset] = 0
			)
			
			/*
			VAR _tbl = 
			FILTER ( 
			    'Date' 
			    , 'Date'[month_offset] = 0
			)
			VAR _result = 
			SUMX ( 
			    _tbl
			    , [Units Sold]
			)
			
			RETURN
			_result
			*/
			```
		displayFolder: Measures\Time Intelligence
		lineageTag: bc69d5fd-3d21-4dea-b3af-29b3dfc588bb

	measure 'Units WTD' = ```
			
			CALCULATE ( 
			    [Units Sold]
			    , 'Date'[week_offset] = -1
			)
			
			/*
			VAR _tbl = 
			FILTER ( 
			    'Date' 
			    , 'Date'[week_offset] = -1
			)
			VAR _result = 
			SUMX ( 
			    _tbl
			    , [Units Sold]
			)
			
			RETURN
			_result
			*/
			```
		displayFolder: Measures\Time Intelligence
		lineageTag: c244df9a-2fe1-4405-84a8-11d05c616161

	measure 'Units PWTD' = ```
			
			CALCULATE ( 
			    [Units Sold]
			    , 'Date'[week_offset] = 0
			)
			
			/*
			VAR _tbl = 
			FILTER ( 
			    'Date' 
			    , 'Date'[week_offset] = 0
			)
			VAR _result = 
			SUMX ( 
			    _tbl
			    , [Units Sold]
			)
			
			RETURN
			_result
			*/
			```
		displayFolder: Measures\Time Intelligence
		lineageTag: 996b9306-3f83-4737-bcfb-a074a1239b0a

	column InvoiceTransID
		dataType: int64
		displayFolder: Columns
		lineageTag: 2cb6b067-ea4a-4461-83a6-89d8cb3076c2
		summarizeBy: count
		sourceColumn: InvoiceTransID

		annotation SummarizationSetBy = Automatic

	column 'Invoice Code'
		dataType: int64
		displayFolder: Columns
		lineageTag: 6828b4f9-9870-41fd-aeb5-c077c710da3a
		summarizeBy: count
		sourceColumn: Invoice Code

		annotation SummarizationSetBy = Automatic

	column 'Invoice Date'
		dataType: dateTime
		formatString: M/d/yyyy
		displayFolder: Columns
		lineageTag: bb672303-9ef0-406d-8c36-9577deefa4e6
		summarizeBy: none
		sourceColumn: Invoice Date

		annotation UnderlyingDateTimeDataType = Date

	column CustomerID
		dataType: int64
		displayFolder: Columns
		lineageTag: 9c134e23-469d-4c72-b718-010df7f23991
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		displayFolder: Columns
		lineageTag: cb6a7139-c183-4a7b-a4e0-1a0821facc2c
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column Units
		dataType: int64
		displayFolder: Columns
		lineageTag: a23e815c-4d88-48aa-b80e-51be4d2c071c
		summarizeBy: sum
		sourceColumn: Units

		annotation SummarizationSetBy = Automatic

	column MSRP
		dataType: double
		displayFolder: Columns
		lineageTag: 318882b0-bdae-418b-b03e-1c6aa5cfe54e
		summarizeBy: sum
		sourceColumn: MSRP

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		displayFolder: Columns
		lineageTag: 945a1cc6-8339-4c0b-b2ac-a19eeb8617cf
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

	column ExtPrice
		dataType: double
		displayFolder: Columns
		lineageTag: 114e1ee8-e5b4-4cb8-b6f1-77890e02a823
		summarizeBy: sum
		sourceColumn: ExtPrice

		annotation SummarizationSetBy = Automatic

	partition Invoice = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\austi\OneDrive - elevatedbi.com\Elevated BI\Power BI\BevBridge\dummy Encompass data\InvoiceTrans.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Removed Columns" = Table.RemoveColumns(#"Promoted Headers",{"Discount", "Discount2", "Participation", "Participation2", "Deposit", "LaidInCost", "TaxCost", "TaxCost2", "WholesaleUnitsPerCase", "LoadSheetLocationID"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"InvoiceID", "Invoice Code"}, {"LoadSheetDate", "Invoice Date"}, {"NumUnits", "Units"}, {"FullPrice", "MSRP"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"InvoiceTransID", Int64.Type}, {"Invoice Code", Int64.Type}, {"Invoice Date", type date}, {"CustomerID", Int64.Type}, {"ProductID", Int64.Type}, {"Units", Int64.Type}, {"MSRP", type number}, {"UnitPrice", type number}, {"ExtPrice", type number}}),
				    #"Sorted Rows" = Table.Sort(#"Changed Type",{{"Invoice Date", Order.Descending}})
				in
				    #"Sorted Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

